In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
#Vocabulary Size
voc_size=10000

In [ ]:
#One Hot Representation
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[2889, 3418, 7554, 127], [2889, 3418, 7554, 5881], [2889, 8362, 7554, 1278], [5958, 9874, 5358, 4092, 3154], [5958, 9874, 5358, 4092, 426], [4937, 2889, 7285, 7554, 2381], [171, 6041, 6802, 4092]]


In [ ]:
#Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np


In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2889 3418 7554  127]
 [   0    0    0    0 2889 3418 7554 5881]
 [   0    0    0    0 2889 8362 7554 1278]
 [   0    0    0 5958 9874 5358 4092 3154]
 [   0    0    0 5958 9874 5358 4092  426]
 [   0    0    0 4937 2889 7285 7554 2381]
 [   0    0    0    0  171 6041 6802 4092]]


In [ ]:
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

[[[-0.01143537 -0.04209286 -0.04268973 -0.031748   -0.00096743
    0.02578001 -0.03694105 -0.03346021  0.01011355 -0.0119875 ]
  [-0.01143537 -0.04209286 -0.04268973 -0.031748   -0.00096743
    0.02578001 -0.03694105 -0.03346021  0.01011355 -0.0119875 ]
  [-0.01143537 -0.04209286 -0.04268973 -0.031748   -0.00096743
    0.02578001 -0.03694105 -0.03346021  0.01011355 -0.0119875 ]
  [-0.01143537 -0.04209286 -0.04268973 -0.031748   -0.00096743
    0.02578001 -0.03694105 -0.03346021  0.01011355 -0.0119875 ]
  [-0.00722613  0.02184935  0.04225126 -0.03281172 -0.008226
    0.0142081   0.03131709  0.04204173 -0.00415958 -0.02714782]
  [-0.01350781  0.02859462 -0.00555874  0.02973405  0.01153107
    0.034057    0.03595021  0.01589043  0.02926217 -0.00230879]
  [-0.01819753  0.04886441  0.00634478 -0.01010423 -0.00609703
    0.02903048 -0.00586896 -0.01980838 -0.02090943 -0.01023971]
  [-0.0372722   0.0249466   0.01938448  0.01817341 -0.00897866
    0.0371024   0.02026265 -0.0015975   0.04026849